defaults:
  con:
    database: emma
    host: mysql_emma
    password: root
    user: root
  queues:
  - queue: API_RESPONSE
    queue_maxsize: 1
  - queue: RESPONSE
    queue_maxsize: 1
  - queue: CONSOLE
    queue_maxsize: 0
  secure_queues:
  - queue: SECURE_NET_SESSIONS
    queue_maxsize: 0
    
  Threads:
    - args:
      - queue_handler
      - event_handler
      autorestart: true
      autostart: true
      endpoint: app.system.core._logger
      queue: LOGGING
      queue_maxsize: 0
      thread_is_daemon: false
      thread_name: T0_LOGGER

    - args:
      - queue_handler
      autorestart: true
      autostart: true
      endpoint: app.system.core._console
      thread_is_daemon: false
      thread_name: T0_CONSOLE
      visible: false

    - args:
      - queue_handler
      - event_handler
      autorestart: true
      autostart: true
      endpoint: app.system.admin.agents.db
      queue: WITHELIST_AGENT
      queue_maxsize: 0
      thread_is_daemon: false
      thread_name: T1_WITHELIST

    - args:
      - queue_handler
      - event_handler
      autorestart: true
      autostart: true
      endpoint: app.system.admin.agents.db
      queue: DB_AGENT
      queue_maxsize: 0
      thread_is_daemon: false
      thread_name: T1_DB

    - args:
      - queue_handler
      - event_handler
      - thread_handler
      autorestart: true
      autostart: true
      endpoint: app.system.admin.routers._command
      queue: COMMAND
      queue_maxsize: 0
      thread_is_daemon: false
      thread_name: T2_COMMANDS

    - args:
      - queue_handler
      - event_handler
      autorestart: true
      autostart: true
      endpoint: app.system.admin.routers._input
      thread_is_daemon: false
      thread_name: T2_INPUT

    - args:
      - queue_handler
      autorestart: true
      autostart: true
      endpoint: app.services.core.gpt
      queue: GPT_INPUT
      queue_maxsize: 1
      thread_is_daemon: false
      thread_name: T3_GPT
      
    - args:
      - queue_handler
      - event_handler
      autorestart: true
      autostart: true
      endpoint: app.services.core.api_user
      queue: API_INPUT
      queue_maxsize: 0
      thread_is_daemon: false
      thread_name: T3_API_IO

#   - args:
#      - queue_handler
#      - event_handler
#      autorestart: true
#      autostart: true
#      endpoint: app.services.core.api_streaming
#      queue: API_STREAMING
#      queue_maxsize: 0
#      thread_is_daemon: false
#      thread_name: T3_API_STREAMING


version: 1.0
