defaults:
  con:
    database: emma
    host: mysql_emma
    password: root
    user: root
  queues:
  - 
  secure_queues:
  - queue: SECURE_NET_SESSIONS
    queue_maxsize: 0
    
  Threads:
    - args:
      - queue_handler
      - event_handler
      autorestart: true
      autostart: true
      endpoint: app.system.core._logger
      queue: LOGGING
      queue_maxsize: 0
      thread_is_daemon: false
      thread_name: T0_LOGGER

    - args:
      - queue_handler
      autorestart: true
      autostart: true
      endpoint: app.system.core._console
      queue: CONSOLE
      queue_maxsize: 0
      thread_is_daemon: false
      thread_name: T0_CONSOLE
      visible: false

    - args:
      - queue_handler
      - event_handler
      - thread_handler
      autorestart: true
      autostart: true
      endpoint: app.system.admin.routers._command
      queue: COMMAND
      queue_maxsize: 0
      thread_is_daemon: false
      thread_name: T2_COMMANDS

    - args:
      - queue_handler
      - event_handler
      autorestart: true
      autostart: true
      endpoint: app.system.admin.routers._input
      thread_is_daemon: false
      thread_name: T2_INPUT

    - args:
      - queue_handler
      autorestart: true
      autostart: true
      endpoint: app.services.external.gpt
      queue: 
      - GPT_INPUT
      - GPT_RESPONSE
      queue_maxsize: 
      - 0
      - 0
      thread_is_daemon: false
      thread_name: T3_GPT

    - args:
      - queue_handler
      - event_handler
      autorestart: true
      autostart: true
      endpoint: app.services.external.aidoc_reader
      queue: 
      - AIDOC_READER
      - AIDOC_READER_QUESTION
      - AIDOC_READER_RESPONSE
      queue_maxsize: 
      - 0
      - 0
      - 0
      thread_is_daemon: false
      thread_name: T3_AI_DOC
      
    - args:
      - queue_handler
      - event_handler
      autorestart: true
      autostart: True
      endpoint: app.services.api.web_api
      queue: 
      - WEB_API_TEXT
      - WEB_API_DOC
      - WEB_API_RESPONSE
      queue_maxsize: 
      - 0
      - 0
      - 0
      thread_is_daemon: false
      thread_name: T3_WEB_API

    - args:
      - queue_handler
      - event_handler
      autorestart: true
      autostart: true
      endpoint: app.services.api.telegram_api
      queue:
      - TELEGRAM_API_TEXT
      - TELEGRAM_API_DOC
      - TELEGRAM_API_RESPONSE
      queue_maxsize: 
      - 0
      - 0
      - 0
      thread_is_daemon: false
      thread_name: T3_TELEGRAM_API

#   - args:
#      - queue_handler
#      - event_handler
#      autorestart: true
#      autostart: true
#      endpoint: app.services.core.api_streaming
#      queue: API_STREAMING
#      queue_maxsize: 0
#      thread_is_daemon: false
#      thread_name: T3_API_STREAMING


#   - args:
#      - queue_handler
#      - event_handler
#      autorestart: true
#      autostart: true
#      endpoint: app.system.admin.agents.db
#      queue: WITHELIST_AGENT
#      queue_maxsize: 0
#      thread_is_daemon: false
#      thread_name: T1_WITHELIST

#    - args:
#      - queue_handler
#      - event_handler
#      autorestart: true
#      autostart: true
#      endpoint: app.system.admin.agents.db
#      queue: DB_AGENT
#      queue_maxsize: 0
#      thread_is_daemon: false
#      thread_name: T1_DB


version: 1.0
