version: 1.0

defaults:
  con:
    host: mysql_emma
    database: emma
    user: root
    password: root
 
  services: 
    - queue: COMMAND
      queue_maxsize: 0
      endpoint: sys_v_cm
      args: 
        - console
        - queue
        - thread
      thread_name: T0_COMMANDS
      thread_is_daemon: True
      autostart: True
      autorestart: True

    - endpoint: sys_v_ir
      args: 
        - console
        - queue
      thread_name: T0_INPUT_ROUTER
      thread_is_daemon: True
      autostart: True
      autorestart: True

    - queue: API_INPUT
      queue_maxsize: 0
      endpoint: services_api_user_io
      args: 
        - console
        - queue
      thread_name: T0_USER_API_IO
      thread_is_daemon: True
      autostart: True
      autorestart: True

    - queue: GPT_INPUT
      queue_maxsize: 1
      endpoint: services_gpt
      args: 
        - console
        - queue
      thread_name: T1_GPT
      thread_is_daemon: True
      autostart: True
      autorestart: True

  queues:
    - queue: CURRENT_INPUT
      queue_maxsize: 1
    - queue: API_RESPONSE
      queue_maxsize: 1
    - queue: RESPONSE
      queue_maxsize: 1
    - queue: CONSOLE
      queue_maxsize: 0
  
  speech_recognition:
    listening:
      language: 'en'
      model: 'my/Model'
    talking:
      language: 'en'
      model: 'my/model'
      tts_mode: 'low' #low to send just text, high to send the audio
      rate: 125
      volume: 1

