version: 1.0

defaults:
  con:
    host: mysql_emma
    database: emma
    user: root
    password: root
 
  services: 
    - queue: LOGGING
      queue_maxsize: 0
      endpoint: logger
      args: 
        - queue
        - events
      thread_name: T0_LOGGER
      thread_is_daemon: True
      autostart: True
      autorestart: True

    - queue: COMMAND
      queue_maxsize: 0
      endpoint: command_router
      args: 
        - console
        - queue
        - events
        - thread
      thread_name: T0_COMMANDS
      thread_is_daemon: True
      autostart: True
      autorestart: True

    - queue: PROTO_SESSIONS
      queue_maxsize: 0
      endpoint: session_protocols
      args: 
        - console
        - queue
        - events
      thread_name: T0_PROTO_SESSIONS
      thread_is_daemon: True
      autostart: True
      autorestart: True

    - endpoint: io_router
      args: 
        - console
        - queue
        - events
      thread_name: T0_INPUT_ROUTER
      thread_is_daemon: True
      autostart: True
      autorestart: True

    - queue: API_INPUT
      queue_maxsize: 0
      endpoint: services_api_user_io
      args: 
        - console
        - queue
        - events
      thread_name: T0_USER_API_IO
      thread_is_daemon: True
      autostart: True
      autorestart: True

    - queue: API_STREAMING
      queue_maxsize: 0
      endpoint: services_api_streaming
      args: 
        - console
        - queue
        - events
      thread_name: T1_USER_API_STREAMING
      thread_is_daemon: True
      autostart: True
      autorestart: True

    - queue: GPT_INPUT
      queue_maxsize: 1
      endpoint: services_gpt
      args: 
        - console
        - queue
      thread_name: T0_GPT
      thread_is_daemon: True
      autostart: True
      autorestart: True

  queues:
    - queue: API_RESPONSE
      queue_maxsize: 1
    - queue: RESPONSE
      queue_maxsize: 1


  secure_queues:
    - queue: SECURE_NET_SESSIONS
      queue_maxsize: 0
  