version: 1.0

defaults:
  con:
    host: mysql_emma
    database: emma
    user: root
    password: root
 
  services: 
    - queue: COMMANDS
      queue_maxsize: 0
      endpoint: sys_v_cm
      args: 
        - queue
        - console
        - thread
      thread_name: T0_COMMANDS
      thread_is_daemon: True
      autostart: True

    - queue: TALKING
      queue_maxsize: 0
      endpoint: services_comunication_tg
      args: 
        - queue
        - console
      thread_name: T1_TALKING
      thread_is_daemon: True
      autostart: True
    
    - queue: null
      queue_maxsize: 0
      endpoint: services_comunication_lg
      args: 
        - queue
        - console
      thread_name: T1_LISTENING
      thread_is_daemon: True
      autostart: True

    - queue: SERVERDATA
      queue_maxsize: 1
      endpoint: web_server
      args: 
        - queue
        - console
      thread_name: T0_WEB_SERVER
      thread_is_daemon: False
      autostart: True


  queues:
    - queue: CURRENT_INPUT
      queue_maxsize: 1
    - queue: ISTK
      queue_maxsize: 1
    - queue: CONSOLE
      queue_maxsize: 0
  
  speech_recognition:
    listening:
      language: 'en'
      model: 'my/Model'
    talking:
      language: 'en'
      model: 'my/model'
      rate: 125
      volume: 1

