user:
  name: 'USERNAME'
  age: 100
  language: 'en'
  level: 10
  timezone: utc

preferences:
  stay_signed_in: True
  manage_os: True
  performance: 'HIGH'
  max_ram: 2048
  clear_temp: True
  max_cache: 'AUTO'
  tts_mode: 'low'
