---
apiVersion: "v1"
kind: "Namespace"
metadata:
  name: "emma"
---
apiVersion: "v1"
kind: "ConfigMap"
metadata:
  name: "emma-config-odlw"
  namespace: "emma"
  labels:
    app: "emma"
data:
  GOOGLE_API_KEY: "AIzaSyAWE6advew5ze_OM6WqQBxag9m_Wpl1V0U"
  OPENAI_API_KEY: "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"
  TELEGRAM_WEBHOOK_SECRET: "FJB5PTPdKH6jxaBwm_Wpl1V0U"
  TELEGRAM_BOT_API_TOKEN: "7043619976:AAHa1x9nm2ooqdyxIRoS2V6ud7Np81C82PI"
  WHATSAPP_BUSINESS_TOKEN: "314529168401421"
  WHATSAPP_PHONE_ID: "253767711162169"
  WHATSAPP_WEBHOOK_SECRET: "FJB5PTPdKH6jxqaBwmPW2_Wpl1V0U"
---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "emma"
  namespace: "emma"
  labels:
    app: "emma"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "emma"
  template:
    metadata:
      labels:
        app: "emma"
    spec:
      containers:
      - name: "github-itsmaper-emma-1"
        image: "gcr.io/perceptive-map-419512/github_itsmaper_emma:$SHORT_SHA"
        env:
        - name: "GOOGLE_API_KEY"
          valueFrom:
            configMapKeyRef:
              key: "GOOGLE_API_KEY"
              name: "emma-config-odlw"
        - name: "OPENAI_API_KEY"
          valueFrom:
            configMapKeyRef:
              key: "OPENAI_API_KEY"
              name: "emma-config-odlw"
        - name: "TELEGRAM_WEBHOOK_SECRET"
          valueFrom:
            configMapKeyRef:
              key: "TELEGRAM_WEBHOOK_SECRET"
              name: "emma-config-odlw"
        - name: "TELEGRAM_BOT_API_TOKEN"
          valueFrom:
            configMapKeyRef:
              key: "TELEGRAM_BOT_API_TOKEN"
              name: "emma-config-odlw"
        - name: "WHATSAPP_BUSINESS_TOKEN"
          valueFrom:
            configMapKeyRef:
              key: "WHATSAPP_BUSINESS_TOKEN"
              name: "emma-config-odlw"
        - name: "WHATSAPP_PHONE_ID"
          valueFrom:
            configMapKeyRef:
              key: "WHATSAPP_PHONE_ID"
              name: "emma-config-odlw"
        - name: "WHATSAPP_WEBHOOK_SECRET"
          valueFrom:
            configMapKeyRef:
              key: "WHATSAPP_WEBHOOK_SECRET"
              name: "emma-config-odlw"
---
apiVersion: "autoscaling/v2"
kind: "HorizontalPodAutoscaler"
metadata:
  name: "emma-hpa-kk1u"
  namespace: "emma"
  labels:
    app: "emma"
spec:
  scaleTargetRef:
    kind: "Deployment"
    name: "emma"
    apiVersion: "apps/v1"
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: "Resource"
    resource:
      name: "cpu"
      target:
        type: "Utilization"
        averageUtilization: 80
