apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    autopilot.gke.io/resource-adjustment: '{"input":{"containers":[{"name":"github-itsmaper-emma-1"}]},"output":{"containers":[{"limits":{"cpu":"500m","ephemeral-storage":"1Gi","memory":"2Gi"},"requests":{"cpu":"500m","ephemeral-storage":"1Gi","memory":"2Gi"},"name":"github-itsmaper-emma-1"}]},"modified":true}'
    autopilot.gke.io/warden-version: 2.8.74
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2024-04-25T01:47:31Z"
  generation: 2
  labels:
    app: emma
  managedFields:
  - apiVersion: apps/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:spec:
        f:replicas: {}
    manager: vpa-recommender
    operation: Update
    subresource: scale
  - apiVersion: apps/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:labels:
          .: {}
          f:app: {}
      f:spec:
        f:progressDeadlineSeconds: {}
        f:revisionHistoryLimit: {}
        f:selector: {}
        f:strategy:
          f:rollingUpdate:
            .: {}
            f:maxSurge: {}
            f:maxUnavailable: {}
          f:type: {}
        f:template:
          f:metadata:
            f:labels:
              .: {}
              f:app: {}
          f:spec:
            f:containers:
              k:{"name":"github-itsmaper-emma-1"}:
                .: {}
                f:env:
                  .: {}
                  k:{"name":"GOOGLE_API_KEY"}:
                    .: {}
                    f:name: {}
                    f:valueFrom:
                      .: {}
                      f:configMapKeyRef: {}
                  k:{"name":"OPENAI_API_KEY"}:
                    .: {}
                    f:name: {}
                    f:valueFrom:
                      .: {}
                      f:configMapKeyRef: {}
                  k:{"name":"TELEGRAM_BOT_API_TOKEN"}:
                    .: {}
                    f:name: {}
                    f:valueFrom:
                      .: {}
                      f:configMapKeyRef: {}
                  k:{"name":"TELEGRAM_WEBHOOK_SECRET"}:
                    .: {}
                    f:name: {}
                    f:valueFrom:
                      .: {}
                      f:configMapKeyRef: {}
                  k:{"name":"WHATSAPP_BUSINESS_TOKEN"}:
                    .: {}
                    f:name: {}
                    f:valueFrom:
                      .: {}
                      f:configMapKeyRef: {}
                  k:{"name":"WHATSAPP_PHONE_ID"}:
                    .: {}
                    f:name: {}
                    f:valueFrom:
                      .: {}
                      f:configMapKeyRef: {}
                  k:{"name":"WHATSAPP_WEBHOOK_SECRET"}:
                    .: {}
                    f:name: {}
                    f:valueFrom:
                      .: {}
                      f:configMapKeyRef: {}
                f:image: {}
                f:imagePullPolicy: {}
                f:name: {}
                f:resources: {}
                f:terminationMessagePath: {}
                f:terminationMessagePolicy: {}
            f:dnsPolicy: {}
            f:restartPolicy: {}
            f:schedulerName: {}
            f:securityContext: {}
            f:terminationGracePeriodSeconds: {}
    manager: GoogleCloudConsole
    operation: Update
    time: "2024-04-25T01:47:31Z"
  - apiVersion: apps/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          f:deployment.kubernetes.io/revision: {}
      f:status:
        f:availableReplicas: {}
        f:conditions:
          .: {}
          k:{"type":"Available"}:
            .: {}
            f:lastTransitionTime: {}
            f:lastUpdateTime: {}
            f:message: {}
            f:reason: {}
            f:status: {}
            f:type: {}
          k:{"type":"Progressing"}:
            .: {}
            f:lastTransitionTime: {}
            f:lastUpdateTime: {}
            f:message: {}
            f:reason: {}
            f:status: {}
            f:type: {}
        f:observedGeneration: {}
        f:readyReplicas: {}
        f:replicas: {}
        f:updatedReplicas: {}
    manager: kube-controller-manager
    operation: Update
    subresource: status
    time: "2024-04-25T01:52:48Z"
  name: emma
  namespace: emma
  resourceVersion: "281920"
  uid: dd9f34ff-f48a-4a79-89dc-b4f67106306b
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: emma
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: emma
    spec:
      containers:
      - env:
        - name: GOOGLE_API_KEY
          valueFrom:
            configMapKeyRef:
              key: GOOGLE_API_KEY
              name: emma-config-q90s
        - name: OPENAI_API_KEY
          valueFrom:
            configMapKeyRef:
              key: OPENAI_API_KEY
              name: emma-config-q90s
        - name: TELEGRAM_WEBHOOK_SECRET
          valueFrom:
            configMapKeyRef:
              key: TELEGRAM_WEBHOOK_SECRET
              name: emma-config-q90s
        - name: TELEGRAM_BOT_API_TOKEN
          valueFrom:
            configMapKeyRef:
              key: TELEGRAM_BOT_API_TOKEN
              name: emma-config-q90s
        - name: WHATSAPP_BUSINESS_TOKEN
          valueFrom:
            configMapKeyRef:
              key: WHATSAPP_BUSINESS_TOKEN
              name: emma-config-q90s
        - name: WHATSAPP_PHONE_ID
          valueFrom:
            configMapKeyRef:
              key: WHATSAPP_PHONE_ID
              name: emma-config-q90s
        - name: WHATSAPP_WEBHOOK_SECRET
          valueFrom:
            configMapKeyRef:
              key: WHATSAPP_WEBHOOK_SECRET
              name: emma-config-q90s
        image: gcr.io/perceptive-map-419512/github_itsmaper_emma:28efa55
        imagePullPolicy: IfNotPresent
        name: github-itsmaper-emma-1
        resources:
          limits:
            cpu: 500m
            ephemeral-storage: 1Gi
            memory: 2Gi
          requests:
            cpu: 500m
            ephemeral-storage: 1Gi
            memory: 2Gi
        securityContext:
          capabilities:
            drop:
            - NET_RAW
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      terminationGracePeriodSeconds: 30
      tolerations:
      - effect: NoSchedule
        key: kubernetes.io/arch
        operator: Equal
        value: amd64
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2024-04-25T01:47:34Z"
    lastUpdateTime: "2024-04-25T01:47:34Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2024-04-25T01:47:31Z"
    lastUpdateTime: "2024-04-25T01:47:34Z"
    message: ReplicaSet "emma-696ffb86dd" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 2
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
